### ISSUE TITLE
complie doozer error about protobuf 

### ISSUE THREAD

**Issue by lshmouse** [ha/doozer#18]
go install github.com/ha/doozer 
# github.com/ha/doozer

workspace/go/src/pkg/github.com/ha/doozer/conn.go:184: cannot use &t.req (type *request) as type proto.Message in function argument:
        *request does not implement proto.Message (missing ProtoMessage method)
workspace/go/src/pkg/github.com/ha/doozer/conn.go:198: cannot use &r (type *response) as type proto.Message in function argument:
        *response does not implement proto.Message (missing ProtoMessage method)
workspace/go/src/pkg/github.com/ha/doozer/conn.go:294: undefined: proto.GetInt64
workspace/go/src/pkg/github.com/ha/doozer/conn.go:326: undefined: proto.GetInt64
workspace/go/src/pkg/github.com/ha/doozer/conn.go:412: undefined: proto.GetInt32
workspace/go/src/pkg/github.com/ha/doozer/conn.go:412: undefined: proto.GetInt64
workspace/go/src/pkg/github.com/ha/doozer/err.go:33: cannot call non-function proto.GetString (type struct {})
workspace/go/src/pkg/github.com/ha/doozer/msg.pb.go:127: cannot use this (type *request) as type proto.Message in function argument:
        *request does not implement proto.Message (missing ProtoMessage method)
workspace/go/src/pkg/github.com/ha/doozer/msg.pb.go:142: cannot use this (type *re

**Comment by sekistner** [comment]
Same problem, is this project still maintained?

**Comment by koodough** [comment]
Same issue

go get -v github.com/ha/doozer

github.com/ha/doozer

# github.com/ha/doozer

/Users/samo/Sites/Go/src/github.com/ha/doozer/conn.go:184: cannot use &t.req (type *request) as type proto.Message in function argument:
        *request does not implement proto.Message (missing ProtoMessage method)
/Users/samo/Sites/Go/src/github.com/ha/doozer/conn.go:198: cannot use &r (type *response) as type proto.Message in function argument:
        *response does not implement proto.Message (missing ProtoMessage method)
/Users/samo/Sites/Go/src/github.com/ha/doozer/conn.go:294: undefined: proto.GetInt64
/Users/samo/Sites/Go/src/github.com/ha/doozer/conn.go:326: undefined: proto.GetInt64
/Users/samo/Sites/Go/src/github.com/ha/doozer/conn.go:412: undefined: proto.GetInt32
/Users/samo/Sites/Go/src/github.com/ha/doozer/conn.go:412: undefined: proto.GetInt64
/Users/samo/Sites/Go/src/github.com/ha/doozer/err.go:33: undefined: proto.GetString
/Users/samo/Sites/Go/src/github.com/ha/doozer/msg.pb.go:10: undefined: proto.GetString
/Users/samo/Sites/Go/src/github.com/ha/doozer/msg.pb.go:127: cannot use this (type *request) as type proto.Message in function argument:
        *request does not implement proto.Message (missing ProtoMessage method)
/Users/samo/Sites/Go/src/github.com/ha/doozer/msg.pb.go:142: cannot use this (type *response) as type proto.Message in function argument:
        *response does not implement proto.Message (missing ProtoMessage method)
/Users/samo/Sites/Go/src/github.com/ha/doozer/msg.pb.go:142: too many errors

**Comment by bketelsen** [comment]
there's a separate issue with pull request that fixes this.  closing/dup
