### ISSUE TITLE
Can't get rev of individual path

### ISSUE THREAD

**Issue by darkhelmet** [ha/doozer#22]
The `rev` command is expecting no arguments. Changing `Rev()` in `conn.go` to accept and send along a path in `t.req.Path` still ends up returning the store rev.

Should this get the rev of an individual path like the help suggests, or are the docs wrong?

**Comment by mreiferson** [comment]
isn't this essentially what #3 was intended to provide (which, most likely, may end up as a separate command so that the existing API does not change)?

**Comment by cespare** [comment]
The command doc is wrong. The `Rev()` api call [is supposed to return the current store rev](http://godoc.org/github.com/ha/doozer#Conn.Rev) and it's also the way the protocol is supposed to behave (see the [protocol document](https://github.com/cespare/doozerd/blob/master/doc/proto.md#verbs)).

If you want the rev for a path, use the `stat` command.

I've also opened PR #31 to add the `getr` command which returns the body and rev for a particular path.

**Comment by mreiferson** [comment]
being handled in either #3 or #31 :smile:
