### ISSUE TITLE
go get doesn't work

### ISSUE THREAD

**Issue by darkhelmet** [ha/doozer#23]
Before I go messing with the readme or whatever else...

`go get github.com/ha/doozer` works, provided the protobuf package can be pulled down, which for me, didn't happen. Getting `x509 signed by unknown authority` stuff. Had to hg clone it manually.

`go get github.com/ha/doozer/cmd` should be `go get github.com/ha/doozer/cmd/doozer` but that also doesn't work, because it of course needs `vers.go`. Have to create it by hand, because the Makefile stuff is gone.

This is with go 1.0.3

**Comment by mreiferson** [comment]
1. are you on OSX?  the first issue might be related to you not building go with support for cgo (which is required for OSX root cert checking).
2. I intended to open a separate issue to discuss versioning schemes to replace the old scripted git hash based scheme to resolve this issue.  I propose semver.

**Comment by darkhelmet** [comment]
Yes, on OSX, but I didn't compile go with anything special. `go env` show `CGO_ENABLED="1"` though I don't know if that's what the toolchain was compiled with...

**Comment by darkhelmet** [comment]
Apparently it was compiled at some point without CGO. Was playing with a cross compile tool, so that probably did it.

**Comment by mreiferson** [comment]
see #24

**Comment by cespare** [comment]
Hmm, seems like we still need to solve the problem that the front page of the readme says:

```
$ go get github.com/ha/doozer/cmd
```

which doesn't work. Suggestions? Just remove that? Change to

```
$ go get github.com/ha/doozer/cmd/doozer
```

?

**Comment by cespare** [comment]
I opened a PR, see #25.
